
-- Connect to db
CONNECT TO CPEDB;

-- Create Schema
CREATE SCHEMA DOSSA;
SET SCHEMA DOSSA;

-- Create 256MB GCD buffer pool
CREATE Bufferpool DOSSA_DATA_BP IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;
CREATE Bufferpool DOSSA_INDX_BP IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;

-- Create additional buffer pools
CREATE Bufferpool DOSSA_LOB_BP IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;
CREATE Bufferpool DOSSA_TEMP_BP IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;
CREATE Bufferpool DOSSA_SYS_BP IMMEDIATE SIZE AUTOMATIC PAGESIZE 32K;

CREATE STOGROUP DOSSADATA_SG ON '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/datafs1', '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/datafs2', '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/datafs3';
CREATE STOGROUP DOSSAINDX_SG ON '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/indexfs1', '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/indexfs2';
CREATE STOGROUP DOSSALOB_SG ON '/home/db2inst1/db2inst1/NODE0000/CPEDB/DOSSA/lobfs1';

-- Create table spaces
CREATE LARGE TABLESPACE DOSSA_DATA_TS PAGESIZE 32 K
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP DOSSADATA_SG
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14
BUFFERPOOL DOSSA_DATA_BP DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE DOSSA_IDX_TS PAGESIZE 32 K
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP DOSSAINDX_SG
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14
BUFFERPOOL DOSSA_INDX_BP DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE DOSSA_LOB_TS PAGESIZE 32 K
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP DOSSALOB_SG
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14
BUFFERPOOL DOSSA_LOB_BP DROPPED TABLE RECOVERY ON;

CREATE USER TEMPORARY TABLESPACE DOSSA_TEMP_TS PAGESIZE 32 K
MANAGED BY AUTOMATIC STORAGE
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14
BUFFERPOOL DOSSA_TEMP_BP;

CREATE SYSTEM TEMPORARY TABLESPACE DOSSA_SYSTMP_TS PAGESIZE 32 K
MANAGED BY AUTOMATIC STORAGE
EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14
BUFFERPOOL DOSSA_SYS_BP;

GRANT USE OF TABLESPACE DOSSA_DATA_TS TO user bpmdbadm;
GRANT USE OF TABLESPACE DOSSA_IDX_TS TO user bpmdbadm;
GRANT USE OF TABLESPACE DOSSA_LOB_TS TO user bpmdbadm;
GRANT USE OF TABLESPACE DOSSA_TEMP_TS TO user bpmdbadm;

--GRANT IMPLICIT_SCHEMA ON DATABASE TO user db2admin;


-- Optionally, grant GROUP access to table spaces
-- GRANT CREATETAB,CONNECT ON DATABASE  TO GROUP DB2USERS;
-- GRANT USE OF TABLESPACE USERTEMP1 TO GROUP DB2USERS;
-- GRANT USE OF TABLESPACE USERSPACE1 TO GROUP DB2USERS;

-- Close connection
CONNECT RESET;