
-- Create the database:
CREATE DATABASE CPEDB
 USING CODESET UTF-8 TERRITORY US 
 COLLATE USING SYSTEM 
 PAGESIZE 32768 
 CATALOG TABLESPACE MANAGED BY AUTOMATIC STORAGE 
 TEMPORARY TABLESPACE MANAGED BY AUTOMATIC STORAGE 
 USER TABLESPACE MANAGED BY AUTOMATIC STORAGE 
;


-- Increase the application heap size
UPDATE DATABASE CONFIGURATION FOR CPEDB USING APPLHEAPSZ 2560;

-- Connect to db
CONNECT TO CPEDB;

-- Drop unnecessary default table spaces
DROP TABLESPACE USERSPACE1;

UPDATE DB CFG FOR CPEDB USING LOGFILSIZ 16384 DEFERRED;
UPDATE DB CFG FOR CPEDB USING LOGSECOND 64 IMMEDIATE;

GRANT CREATETAB,CONNECT,DBADM ON DATABASE TO user bpmdbadm;
GRANT SELECT ON SYSIBM.SYSVERSIONS TO user bpmdbadm;
GRANT SELECT ON SYSCAT.DATATYPES TO user bpmdbadm;
GRANT USAGE on WORKLOAD SYSDEFAULTUSERWORKLOAD TO user bpmdbadm;
UPDATE DATABASE CONFIGURATION FOR CPEDB USING NEWLOGPATH '/home/db2inst1/db2inst1/NODE0000/CPEDB/log';
ALTER BUFFERPOOL IBMDEFAULTBP IMMEDIATE SIZE 250 AUTOMATIC;

-- Close connection
CONNECT RESET;